### ISSUE TITLE
KeyError: 'standard_id' on traverse all implicit relationships

### ISSUE THREAD

**Issue by phdowling** [amr-cossi/opencti-maltego#8]
Running the "Malware to all Entities" relationship on demo.opencti.io, using Emotet (`malware--36297121-bf18-56e1-b200-d39c9f9f5cee`) as input:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/maltego_trx/server.py", line 45, in run_transform
    return transform_method.run_transform(client_msg), 200  # Transform class
  File "/usr/local/lib/python3.8/site-packages/maltego_trx/transform.py", line 12, in run_transform
    cls.create_entities(request, response)
  File "/var/www/TRX/transforms/openctimalwareStixDomainEntityToStixDomainEntity.py", line 12, in create_entities
    opencti_transform("StixDomainEntityToStixDomainEntity", None, request, response)
  File "/var/www/TRX/opencti/openctitransform.py", line 273, in opencti_transform
    neighbour_entity = addStixEntity(
  File "/var/www/TRX/opencti/addEntities.py", line 38, in addStixEntity
    if opencti_entity["standard_id"].startswith("identity--"):
KeyError: 'standard_id'

```
This of course makes the Transform fail.

In other news though, the grouped API calls are hugely speeding up the integration, very awesome!

**Comment by amr-cossi** [comment]
Thanks for the tests.
I wasn't testing with the open demo so this case was not obvious on my side my I had several issues when Observables were directly linked to Domain Entities.
The errors should be gone, but I'm still investigating a bug on OpenCTI side, where relations are not properly filtered when I query for "Stix-Domain-Object" only on one side. In the current version, it may just return less info than 2*limit because some relations are filtered after the query.

**Comment by amr-cossi** [comment]
Waiting on https://github.com/OpenCTI-Platform/client-python/issues/158
